# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event_leave_room.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import room_event_pb2 as room__event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x65vent_leave_room.proto\x1a\x10room_event.proto\"K\n\x0f\x45vent_LeaveRoom\x12\x0c\n\x04name\x18\x01 \x01(\t2*\n\x03\x65xt\x12\n.RoomEvent\x18\xe8\x07 \x01(\x0b\x32\x10.Event_LeaveRoom')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_leave_room_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  room__event__pb2.RoomEvent.RegisterExtension(_EVENT_LEAVEROOM.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _EVENT_LEAVEROOM._serialized_start=44
  _EVENT_LEAVEROOM._serialized_end=119
# @@protoc_insertion_point(module_scope)
