# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response_replay_get_code.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eresponse_replay_get_code.proto\x1a\x0eresponse.proto\"_\n\x16Response_ReplayGetCode\x12\x13\n\x0breplay_code\x18\x01 \x01(\t20\n\x03\x65xt\x12\t.Response\x18\xce\x08 \x01(\x0b\x32\x17.Response_ReplayGetCode')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'response_replay_get_code_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  response__pb2.Response.RegisterExtension(_RESPONSE_REPLAYGETCODE.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _RESPONSE_REPLAYGETCODE._serialized_start=50
  _RESPONSE_REPLAYGETCODE._serialized_end=145
# @@protoc_insertion_point(module_scope)
