name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - CI
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          submodules: 'true'
      - name: dependencies
        run: |
          echo "podman version"
          podman --version
          sudo apt-get update
          sudo apt-get install -y python3.10 python3-pip podman
          echo "podman version"
          podman --version
          echo "running containers"
          ./tests/testatrice/testatrice.sh --sleep 60
          pip install .
          pip install .[test]
      - name: tests
        run: python3 -m unittest discover ./tests
