name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - CI
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3.10 python3-pip podman
          git submodule update
          echo "running containers"
          ./tests/testatrice/testatrice.sh --sleep 60 > /dev/null
          pip install .
          pip install .[test]
      - name: tests
        run: python3 -m unittest discover ./tests
