name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - CI
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          submodules: 'true'
      - name: dependencies
        run: |
          cd ./tests/testatrice
          ./testatrice.sh --sleep 60
          cd ../..
          pip install .
          pip install .[test]
      - name: tests
        run: python3 -m unittest discover ./tests
